### ISSUE TITLE
updates on fedscale and oort

### ISSUE THREAD

**Issue by liecn** [SymbioticLab/Kuiper#2]
Hi,

I notice the fedscale provides the data for oort. And the fedscale on GitHub has been updated. For example, the device info is splited into client_behave_trace and client_device_capacity while oort still uses client_profile.pkl. Besides, there are also some differences between the configurations for tasks.

To make the oort correct, I guess I have to use the old version of fedscale, right? Say, commit before May 24th. Or you'll update oort later?

Thanks.

**Comment by Romero027** [comment]
Hi @liecn,

We plan to update Oort soon (hopefully in the next few weeks). In the meantime, feel free to use Fedscale and let us know if you have any questions! 

Thanks, Xiangfeng
