### ISSUE TITLE
issues on plot_perf.py

### ISSUE THREAD

**Issue by liecn** [SymbioticLab/Kuiper#3]
Hi,

It said we can reproduce figs 11 and 12 in the readme. But I only get the plot_perf.py to reproduce the line figures. 

Could you please provide the plot.py for the bar figures for fair comparison?
![image](https://user-images.githubusercontent.com/32219716/128436625-1d607cfb-161c-427c-b078-d87d002ef67c.png)

Thank you so much!

Best

**Comment by fanlai0990** [comment]
Unfortunately, we do not have this script as it covers too many experiments and various knobs. :(
