### ISSUE TITLE
<download_resuslts.sh> G-Drive links not working

### ISSUE THREAD

**Issue by UvrajSB** [SymbioticLab/Kuiper#4]
#!/bin/bash

gdown -O ./speech_samples_f16.pkl https://drive.google.com/uc?id=1sAnJ-4zySG65JtT47XOXzBHc4zHhgz9C
gdown -O ./openimg_distr.pkl https://drive.google.com/uc?id=1WBQBra_wv2sLU18l4uiq3JgMRcudyfG0
gdown -O ./client_profile.pkl https://drive.google.com/uc?id=1F8qLzUdINPSH_pSsbcr81Ry7-sBY1DVB

These links show 404 error, please confirm if the files and access still intact.

**Comment by Romero027** [comment]
Hi! 

This repo is no longer actively maintained - please refer to [FedScale](https://github.com/SymbioticLab/FedScale/tree/master) for up-to-date datasets.

**Comment by Romero027** [comment]
Closing this issue.

Please join the slack or email us at [fedscale@googlegroups.com](mailto:fedscale@googlegroups.com) if you have any questions!
